### PR TITLE
Allow for modifications of the code to be proposed

### PR DESCRIPTION
**Pull request by benternet**
I wanted to propose a code change, but I wasn't sure if that would be breaking this rule. So I thought we better make that clear first.

### CODE REVIEW

**Comment by mziwisky** [comment]
I think the spirit (and letter) of rule 4 is that you can't make a change that would cause the server to not run the code from this repo.  e.g. you can't change `start.sh` to git pull puppyhoff.me and run that instead of this repo.  So yeah, any merged PR would cause the two to diverge momentarily, but they'd reconverge automatically because the script running on the server will soon pull down the change.

I feel like your proposed change would allow permanent divergence.  It's saying that a change/turn/PR is allowed to make the server run something besides the repo.  Therefore, I reject it.

And I have some questions... (a) I see a "Merge pull request" button on this PR -- can we use github to actually enforce the requirement of unanimous acceptance on a PR?  (b) Should we allow any kind of change requests in the PR process?  Like if Ben has a PR that I think is along the right lines, but I don't like it without a little modification, can I request that here and let him put up a commit on the branch before voting my acceptance?  Or do we play it like once a PR is submitted, we're voting on that thing as-is?  I think the former makes sense.  Basically we're voting on the proposal in the title/description of the PR, but the actual code change may need some back-and-forth before it gets to the state that we agree actually fulfills the intention.

**Comment by benternet** [comment]
re: your questions, (a) yea we should have @kelpycreek turn on https://help.github.com/articles/enabling-required-reviews-for-pull-requests/ (b) AFAIK the idea is that the player has a week to put up a PR that in some form is approved by all other players, so yea comments and multiple iterations make sense to me.

**Comment by benternet** [comment]
Item 4 protects from a change which `causes the code in the repository to diverge from the code on the server`. But nothing actually protects the code on the server from diverging from the repository. But I agree that we should have that explicit protection. But perhaps only so far that it must run `start.sh`. IE I could put anything inside that `start.sh` and that should/would/could be fine.

What if I proposed the following instead:
```
4. No change, other than a turn, shall be made that causes the code in the repository to diverge from the code on the server.
5. No change shall be made that causes the entrypoint of the server to change from the `start.sh` file in this repository.
```

**Comment by kelpycreek** [comment]
@benternet @mziwisky 
You guys are right, the fact that we can merge pull requests is a bug.

The spirit of rule 4 though is that players should NOT change the code in the repository. Instead, the repository is officially managed by the game server, whic decides whether or not to merge pull requests by its own internal logic. So, for example, any player clicking that merge button would be breaking rule 4. Thus, the code and the repository should only ever be out of sync for the time between the server merging the request, and restarting itself.

I'd change it immediately, but it looks like someone found the commit where I accidentally included the gitnomic accounts password (https://github.com/kelpycreek/gitnomic/commit/db639e4615e346f38fd61a87a661596898a06d40)
because I can no longer log in. (Which is fine by me, I was kinda hoping that would happen)

So it's on that person to make the change. (and if they dont change the password BACK by wednesday afternoon then it will most definitely break the game.)

**Comment by benternet** [comment]
Let's continue this discussion here, but since this was more controversial than I anticipated, I created a simpler PR for my first move.

**Comment by kelpycreek** [comment]
@benternet 
Sounds good to me, make sure to close this one before wednesday. Its pretty undefined which one the game will pick up if you have multiple open.

**Comment by mziwisky** [comment]
It occurred to me that there are no punishments defined for breaking the rules.  Do we need some?  And if so, how will they be enforced?  By we fallible humans, or by the cold unsympathetic logic of the machine?  The only punishments that come to mind are point deductions, and capital punishment -- removal from the database.

**Comment by mziwisky** [comment]
Oh, also, how many points are needed for a win?  I didn't see that finish line defined in the code

**Comment by mziwisky** [comment]
I'm totally hijacking this PR for all my random questions

**Comment by benternet** [comment]
Ah I didn't even realize that me pushing the merge button, even if I had received unanimous approvals on my PR, would constitute a rule break. So yea we should probably figure out what the consequences to that are. I propose a reset of score to zero?

If someone is being a jerk though, I imagine we just `/kick` them?

**Comment by benternet** [comment]
Ok how about this one?

**Comment by mziwisky** [comment]
> We have no idea how many points anyone is going to get in what amount of time

True, but we know the initial conditions -- everyone starts at 0 (I guess that's not explicit anywhere... but yeah), merged PRs earn the requestor 10 points, and denied PRs make the requestor lose 10 points.  And rule 6 is definitely ambiguous, but seems to imply that some `n` should be defined as the number of points that are needed to win.  I think it should be something like 500.  That gives us plenty of runway, 50 successful PRs for a win times 6 players, but still is low enough to eventually put some pressure on.  We can always change it with a PR...

Anyway, I kinda feel like the only appropriate punishment is a `/kick`.  Cuz otherwise I could merge a PR that immediately assigns me 1,000,000 points, and then I've won.  And simply resetting to 0 is only a punishment if the user currently has a positive number of points.

I'm starting to feel like a filibusterer.... or maybe just a lawyer.... but I still don't like the phrasing of your change.  It still seems to leave room for a PR to just make the server stop running the code in this repo.  It expressly allows it.  So my proposal for you is this:

> No change shall be made that causes the server to stop running the code in the latest commit of the master branch of the repository.

Simple.  Clear.  Elegant.  Eloquent.  Poetic.  Right???

**Comment by mziwisky** [comment]
re: punishment, and machine enforcement vs human enforcement -- i think that's one of the interesting things about the game, the roles of humans vs machines.  my gut feeling is that "the point" of the game is to make it more and more automated/machine-enforced.  at least in early stages.  but of course, people are free to steer it any direction they want.  in any event, since it doesn't come with codified enforcement out of the box, i think humans have to take on that responsibility, and make "soft implementations" of punishment rules (i.e. styleguide changes as opposed to code changes)

re: winning -- ah, i see the win condition now (it's called `wins` btw, not `is_winner`).  but it looks like it isn't called anywhere.  so i guess a PR is needed to hook that up.

re: kicking/adding -- i agree, that seems like a natural thing to add at some point.

re: affecting the repo -- i agree, ideally the server itself would manage all merging (and perhaps abandoning) of PRs.  maybe we need to remove all of us as collaborators.  let the collaborators list live in the game's DB rather than in github's configuration.

## re: the server being down, @kelpycreek when you gonna fix dat?!

**Comment by kelpycreek** [comment]
Sorry!
Server ip got changed, forgot to update it:
http://35.231.68.2/

Im definitely making a list of how to change the initial implementation. But Im excited to see how we overcome them! At this point Im just praying wednesdays update doesnt crash the server.

**Comment by kelpycreek** [comment]
Also, while this is still the thread for general discussion,

### Game Breaking bug!

I left in a return statement I used for testing on accident. Line 111 in game.py needs to get deleted or the round will never get resolved and the commits will never be merged.

I can change it manually on the server, but cant change it in the gihub repo because, again, Im locked out.

Speaking of which:
If the git_pass in config.json and the password for gitnomicadmin arent the same by wednesday afternoon, it will DEFINITELY never get anywhere. 

Although, ironically, it wont crash because of the return mistake. :P

**Comment by mziwisky** [comment]
Oh snap, not sure where you're hosting it (looks like Google cloud maybe) but should we expect that IP to be changing regularly? Would be nice to get a stable one

**Comment by kelpycreek** [comment]
I don't know if it's going to be changing regularly, or if it was a result
of the restart we did Wednesday when I had to update my payment information.
I should probably just grab a vanity url and set up dns

**Comment by benternet** [comment]
hmmm i just pushed a new change to my `clarify-rules` branch in my forked repo and somehow that closed this PR...not sure why that is. it doesn't appear that anything was merged to any branch in the `gitnomicadmin` org...

**Comment by benternet** [comment]
ohhhh :S

**Comment by benternet** [comment]
To be continued at https://github.com/gitnomicadmin/gitnomic/pull/4. My apologies.

**Pull request closed without merging**
