### PR TITLE
The game must go on

### PR DESCRIPTION
**Pull request by benternet**
As per discussion in https://github.com/gitnomicadmin/gitnomic/pull/2
it has been discovered that gameplay cannot continue without this
change. All players would be maximum sad without rounds resolving and
PRs actually getting merged. So let's let that happen.

### CODE REVIEW

**Review by mziwisky — APPROVED** [review]

**Review by kelpycreek — APPROVED** [review]

**Comment by benternet** [comment]
@bulmaro @yoyo52 @ignatiusbill what do you think?

**Comment by benternet** [comment]
Even though it didn't have quorum?

**Comment by kelpycreek** [comment]
Yeah, its a special case that shouldnt happen again, but one way or another this change needed to be made. I think you get another turn though, since fixing the return statement will only change the code AFTER the restart.

And the return prevents the game from advancing turns.

**Comment by mziwisky** [comment]
Cool.  So did the timer restart on the first turn, then?

**Comment by mziwisky** [comment]
Oh also, the second of the original endpoints doesn't work -- http://35.231.68.2/score/benternet

I noticed that before this restart, and back then it was a

 ```builtins.OSError
OSError: [Errno 5] Input/output error
```

on the line `print(username)`, but now it gets past that line and it's a

```builtins.TypeError
TypeError: 'NoneType' object is not subscriptable
```

which makes me think we're somehow failing to pull players from the db?  Maybe?

**Comment by kelpycreek** [comment]
I dont know why we got different errors before vs after, but the failure is intentional.

Players only get an entry in the db when they get points for the first time. This also is where the 'players start with zero points' thing is explicitly defined.

```
def add_points(username, points):
  #Adds the specified number of points to a player.
  #If the player doesnt exist, adds them with the specified points
  db = get_connection()
  userDB = db.users
  return userDB.update_one({"_id" : username}, {"$inc" : {"points" : points}}, upsert=True)
```

`upsert=True` means that we insert it if a record for 'username' doesnt exist. And $inc will set the value instead of incrementing it if the field doesnt already exist.

So the db currently only has one entry in it, in the game collection.

**Pull request merged**
